[mygis]
# Authentication examples — pick ONE approach

# 1) Use a saved ArcGIS profile (recommended)
profile = "work"

# 2) Or ArcGIS Pro/Home sign-in
# auth = "pro"  # or "home"

# 3) Or explicit portal credentials
# portal_url = "https://example.com/portal"
# username = "alice"
# password = "<SECRET>"

# Optional logging settings
# log_level = "INFO"
# log_format = "plain"  # or "json"
# log_file = "mygis.log"

# Optional: scope hosted services search (examples/list_sync_enabled_services.py)
# search_owner = "me"      # or a username, or "*" for any
